### PR TITLE
I have added Japanese translation

### PR DESCRIPTION
**Pull request by kunichan2013**
I translated main menu and exercises.

### CODE REVIEW

**Comment by isRuslan** [comment]
Thanks for a huge work @kunichan2013! 👍 
But to complete the translation we need to add Japanese version of credits files: `i18n/credits/{ja.header.txt,ja.footer.txt}`, could you finish this?

**Comment by kunichan2013** [comment]
Hello Ruslan,

I pushed new commit with Japanese version of credits files.

Regards,
Kuni Tone

2016年5月8日(日) 18:05 Ruslan Ismagilov notifications@github.com:

**Comment by kunichan2013** [comment]
Thanks!

2016年5月9日(月) 20:45 Ruslan Ismagilov notifications@github.com:

**Comment by isRuslan** [comment]
@kunichan2013 thanks for your effort, this PR is available as `1.6.0` version of `learn-generators`

https://github.com/isRuslan/learn-generators/releases/tag/1.6.0

**Comment by isRuslan** [comment]
@kunichan2013 I also going to add you in **credits** section, so please provide your twitter account if you have some.

**Comment by kunichan2013** [comment]
My twitter account is @kunitone

**Comment by isRuslan** [comment]
Awesome, added and published `1.6.1` version with your credits.
Thanks for your contribution @kunichan2013 👍

**Comment by kunichan2013** [comment]
Thank you so much.

**Pull request merged**
